Forum/Controllers/Forum/CategoryController.cs
using AutoMapper;
using Contracts;
using Entities.DTO.ForumDto;
using Entities.DTO.ForumDto.Create;
using Entities.DTO.ForumDto.Update;
using Entities.Models.Forum;
using Entities.RequestFeatures.Forum;
using Forum.ActionsFilters;
using Forum.ActionsFilters.Forum;
using Forum.ModelBinders;
using Forum.Utility.ForumLinks;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Forum.Controllers.Forum
{
    [Route("api/categories")]
    [ApiController]
    public class CategoryController : ControllerBase
    {
        private readonly IRepositoryManager _repository;
        private readonly ILoggerManager _logger;
        private readonly IMapper _mapper;
        private readonly CategoryLinks _categoryLinks;

        // TODO. Service layer for mappings and data shaping
        public CategoryController(IRepositoryManager repository, ILoggerManager logger, IMapper mapper, CategoryLinks categoryLinks)
        {
            _repository = repository;
            _logger = logger;
            _mapper = mapper;
            _categoryLinks = categoryLinks;
        }
        [HttpOptions]
        public IActionResult GetCategoriesOptions()
        {
            Response.Headers.Add("Allow", "GET, OPTIONS, POST");
            return Ok();
        }
        [HttpGet(Name = "GetCategories")]
        [HttpHead]
        [ServiceFilter(typeof(ValidateMediaTypeAttribute))]
        public async Task<IActionResult> GetCategories([FromQuery] ForumCategoryParameters forumCategoryParameters)
        {
            var categoriesFromDb = await _repository.ForumCategory.GetAllCategoriesAsync(forumCategoryParameters, trackChanges: false);

            Response.Headers.Add("X-Pagination", JsonConvert.SerializeObject(categoriesFromDb.MetaData));

            var categoriesDto = _mapper.Map<IEnumerable<ForumCategoryDto>>(categoriesFromDb);
            var links = _categoryLinks.TryGenerateLinks(categoriesDto, forumCategoryParameters.Fields, HttpContext);

            return links.HasLinks ? Ok(links.LinkedEntities) : Ok(links.ShapedEntities);
        }
        [HttpGet("{categoryId}", Name = "GetCategoryById")]
        [ServiceFilter(typeof(ValidateMediaTypeAttribute))]
        public async Task<IActionResult> GetCategory(int categoryId, [FromQuery] ForumCategoryParameters forumCategoryParameters)
        {
            var category = await _repository.ForumCategory.GetCategoryAsync(categoryId, trackChanges: false);
            if (category == null)
            {
                _logger.LogInfo($"Category with id: {categoryId} doesn't exist in the database.");
                return NotFound();
            }
            else
            {
                var categoryDto = _mapper.Map<ForumCategoryDto>(category);
                var links = _categoryLinks.TryGenerateLinks(new List<ForumCategoryDto>() { categoryDto }, forumCategoryParameters.Fields, HttpContext);

                return links.HasLinks ? Ok(links.LinkedEntities) : Ok(links.ShapedEntities);
            }
        }
        [HttpGet("collection/({ids})", Name = "CategoryCollection")]
        [ServiceFilter(typeof(ValidateMediaTypeAttribute))]
        public async Task<IActionResult> GetCategoryCollection([ModelBinder(BinderType = typeof(ArrayModelBinder))] IEnumerable<int> ids, 
            [FromQuery] ForumCategoryParameters forumCategoryParameters)
        {
            if (ids == null)
            {
                _logger.LogError("Parameter ids is null");
                return BadRequest("Parameter ids is null");
            }

            var categoryEntities = await _repository.ForumCategory.GetCategoriesByIdsAsync(ids, trackChanges: false);

            if (ids.Count() != categoryEntities.Count())
            {
                _logger.LogError("Some ids are not valid in a collection");
                return NotFound();
            }

            var categoriesToReturn = _mapper.Map<IEnumerable<ForumCategoryDto>>(categoryEntities);
            var links = _categoryLinks.TryGenerateLinks(categoriesToReturn, forumCategoryParameters.Fields, HttpContext, ids);

            return links.HasLinks ? Ok(links.LinkedEntities) : Ok(links.ShapedEntities);
        }
        [HttpPost]
        [ServiceFilter(typeof(ValidationFilterAttribute))]
        public async Task<IActionResult> CreateCategory([FromBody] ForumCategoryForCreationDto category)
        {
            var categoryEntity = _mapper.Map<ForumCategory>(category);

            _repository.ForumCategory.CreateCategory(categoryEntity);
            await _repository.SaveAsync();

            var categoryToReturn = _mapper.Map<ForumCategoryDto>(categoryEntity);

            return CreatedAtRoute("GetCategoryById", new { categoryId = categoryToReturn.Id }, categoryToReturn);
        }
        [HttpPost("collection")]
        [ServiceFilter(typeof(ValidationFilterAttribute))]
        public async Task<IActionResult> CreateCategoryCollection([FromBody] IEnumerable<ForumCategoryForCreationDto> categoryCollection)
        {
            if (categoryCollection == null)
            {
                _logger.LogError("Category collection sent from client is null.");
                return BadRequest("Category collection is null");
            }
            var categoryEntities = _mapper.Map<IEnumerable<ForumCategory>>(categoryCollection);
            foreach (var category in categoryEntities)
            {
                _repository.ForumCategory.CreateCategory(category);
            }
            await _repository.SaveAsync();
            var categoryCollectionToReturn = _mapper.Map<IEnumerable<ForumCategoryDto>>(categoryEntities);
            var ids = string.Join(",", categoryCollectionToReturn.Select(c => c.Id));
            return CreatedAtRoute("CategoryCollection", new { ids }, categoryCollectionToReturn);
        }
        [HttpPut("{categoryId}", Name = "UpdateCategory")]
        [ServiceFilter(typeof(ValidationFilterAttribute))]
        [ServiceFilter(typeof(ValidateCategoryExistsAttribute))]
        public async Task<IActionResult> UpdateCategory(int categoryId, [FromBody] ForumCategoryForUpdateDto category)
        {
            // TODO User id for collection PUT

            var categoryEntity = HttpContext.Items["category"] as ForumCategory;

            _mapper.Map(category, categoryEntity);
            await _repository.SaveAsync();
            return NoContent();
        }
        [HttpPatch("{categoryId}", Name = "PartiallyUpdateCategory")]
        [ServiceFilter(typeof(ValidateCategoryExistsAttribute))]
        public async Task<IActionResult> PartiallyUpdateCategory(int categoryId, [FromBody] JsonPatchDocument<ForumCategoryForUpdateDto> patchDoc)
        {
            if (patchDoc == null)
            {
                _logger.LogError("patchDoc object sent from client is null.");
                return BadRequest("patchDoc object is null");
            }
            var categoryEntity = HttpContext.Items["category"] as ForumCategory;

            var categoryToPatch = _mapper.Map<ForumCategoryForUpdateDto>(categoryEntity);
            patchDoc.ApplyTo(categoryToPatch, ModelState);

            TryValidateModel(categoryToPatch);

            if (!ModelState.IsValid)
            {
                _logger.LogError("Invalid model state for the patch document");
                return UnprocessableEntity(ModelState);
            }

            _mapper.Map(categoryToPatch, categoryEntity);

            _logger.LogInfo($"Part up {categoryToPatch.Name}");

            await _repository.SaveAsync();

            return NoContent();
        }
        [HttpDelete("{categoryId}", Name = "DeleteCategory")]
        [ServiceFilter(typeof(ValidateCategoryExistsAttribute))]
        public async Task<IActionResult> DeleteCategory(int categoryId)
        {
            var category = HttpContext.Items["category"] as ForumCategory;

            _repository.ForumCategory.DeleteCategory(category);
            await _repository.SaveAsync();
            return NoContent();
        }
    }
}

Forum/Controllers/Forum/ForumBaseCreationController.cs
using AutoMapper;
using Entities.DTO.ForumDto.Create;
using Entities.ViewModels.Forum;
using Forum.ActionsFilters.Consumer.Forum;
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Forum.Controllers.Forum
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ForumBaseCreationController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRepositoryApiManager _repositoryApiManager;

        public ForumBaseCreationController(IMapper mapper, IRepositoryApiManager repositoryApiManager)
        {
            _mapper = mapper;
            _repositoryApiManager = repositoryApiManager;
        }
        [HttpGet]
        public async Task<IActionResult> RedirectToCreateForumBase(string model)
        {
            if(string.IsNullOrEmpty(model))
                return BadRequest(ModelState);

            var catAddModel = _mapper.Map<ForumBaseCreationView>(JsonConvert.DeserializeObject<ForumHomeViewModel>(model));
            return View("~/Views/Forum/Add/ForumAddForumBase.cshtml", catAddModel);
        }
        [ServiceFilter(typeof(ValidateAuthenticationAttribute))]
        [HttpPost]
        public async Task<IActionResult> RedirectToCreateForumBase(ForumBaseCreationView model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            int userId = (int)HttpContext.Items["userId"];
            var forumToAdd = _mapper.Map<ForumBaseForCreationDto>(model);

            if (userId > 0)
            {
                forumToAdd.ForumUserId = userId;
                var res = await _repositoryApiManager.ForumApis.CreateForumBase(model.SelectedCategoryId, forumToAdd);
                //var resCounter = await _forumService.UpdatePostCounter(categoryId, true);
            }
            else
            {
                return BadRequest("User ID error.");
            }

            return RedirectToAction("ForumHome", "ForumHome");
        }
    }
}

Forum/Controllers/Forum/ForumCategoryCreationController.cs
using AutoMapper;
using Entities.DTO.ForumDto.Create;
using Entities.ViewModels.Forum;
using Forum.ActionsFilters.Consumer.Forum;
using Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Forum.Controllers.Forum
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ForumCategoryCreationController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRepositoryApiManager _repositoryApiManager;

        public ForumCategoryCreationController(IMapper mapper,IRepositoryApiManager repositoryApiManager)
        {
            _mapper = mapper;
            _repositoryApiManager = repositoryApiManager;
        }
        [HttpGet]
        public async Task<IActionResult> RedirectToCreateCategory()
        {
            return View("~/Views/Forum/Add/ForumAddCategory.cshtml");
        }
        [ServiceFilter(typeof(ValidateAuthenticationAttribute))]
        [HttpPost]
        public async Task<IActionResult> RedirectToCreateCategory(ForumCategoryCreationView model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            int userId = (int)HttpContext.Items["userId"];
            var categoryToAdd = _mapper.Map<ForumCategoryForCreationDto>(model);

            if (userId > 0)
            {
                categoryToAdd.ForumUserId = userId;
                var res = await _repositoryApiManager.CategoryApis.CreateForumCategory(categoryToAdd);
            }
            else
            {
                return BadRequest("User ID error.");
            }

            return RedirectToAction("ForumHome", "ForumHome");
        }
    }
}

Forum/Controllers/ForumController.cs
using AutoMapper;
using Contracts;
using Entities.DTO.ForumDto;
using Entities.DTO.ForumDto.Create;
using Entities.DTO.ForumDto.Update;
using Entities.Models.Forum;
using Forum.ActionsFilters;
using Forum.ActionsFilters.Forum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.Design;

namespace Forum.Controllers
{
    [Route("api/categories/{categoryId}/forums")]
    [ApiController]
    public class ForumController : ControllerBase
    {
        private readonly IRepositoryManager _repository;
        private readonly ILoggerManager _logger;
        private readonly IMapper _mapper;

        public ForumController(IRepositoryManager repository, ILoggerManager logger, IMapper mapper)
        {
            _repository = repository;
            _logger = logger;
            _mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> GetForumsForCategory(int categoryId)
        {
            var category = await _repository.ForumCategory.GetCategoryAsync(categoryId, trackChanges: false);

            if (category == null)
            {
                _logger.LogInfo($"Company with id: {categoryId} doesn't exist in the database.");
                return NotFound();
            }

            var forums = await _repository.ForumBase.GetAllForumsAsync(categoryId, trackChanges: false);
            var forumsDto = _mapper.Map<IEnumerable<ForumBaseDto>>(forums);

            return Ok(forumsDto);
        }
        [HttpGet("{forumId}", Name = "GetForumForCategory")]
        public async Task<IActionResult> GetForumForCategory(int categoryId, int forumId)
        {
            var category =  await _repository.ForumCategory.GetCategoryAsync(categoryId, trackChanges: false);
            if (category == null)
            {
                _logger.LogInfo($"Company with id: {categoryId} doesn't exist in the database.");
                return NotFound();
            }
            var forumDb =  await _repository.ForumBase.GetForumAsync(categoryId, forumId, trackChanges: false);
            if (forumDb == null)
            {
                _logger.LogInfo($"Employee with id: {forumId} doesn't exist in the database.");
                return NotFound();
            }
            var forum = _mapper.Map<ForumBaseDto>(forumDb);
            return Ok(forum);
        }
        [HttpPost]
        [ServiceFilter(typeof(ValidationFilterAttribute))]
        public async Task<IActionResult> CreateForumForCategory(int categoryId, [FromBody] ForumBaseForCreationDto forum)
        {
            if (!ModelState.IsValid)
            {
                _logger.LogError("Invalid model state for the EmployeeForCreationDto object");
                return UnprocessableEntity(ModelState);
            }


            var category =  await _repository.ForumCategory.GetCategoryAsync(categoryId, trackChanges: false);
            if (category == null)
            {
                _logger.LogInfo($"Company with id: {categoryId} doesn't exist in the database.");
                return NotFound();
            }

            var forumEntity = _mapper.Map<ForumBase>(forum);
            forumEntity.CreatedAt = DateTime.Now;
            forumEntity.ForumUserId = 1;
            _repository.ForumBase.CreateForumForCategory(categoryId, forumEntity);
            await _repository.SaveAsync();

            var forumToReturn = _mapper.Map<ForumBaseDto>(forumEntity);

            return CreatedAtRoute("GetForumForCategory", new { categoryId, id = forumToReturn.Id }, forumToReturn);
        }
        [HttpDelete("{forumId}")]
        [ServiceFilter(typeof(ValidateForumForCategoryExistsAttribute))]
        public async Task<IActionResult> DeleteForumForCategory(int categoryId, int forumId)
        {
            var forumForCategory = HttpContext.Items["forum"] as ForumBase;

            _repository.ForumBase.DeleteForum(forumForCategory);
            await _repository.SaveAsync();
            return NoContent();
        }
        [HttpPut("{forumId}")]
        [ServiceFilter(typeof(ValidationFilterAttribute))]
        [ServiceFilter(typeof(ValidateForumForCategoryExistsAttribute))]
        public async Task<IActionResult> UpdateForumForCategory(int categoryId, int forumId, [FromBody] ForumBaseForUpdateDto forum)
        {
            var forumEntity = HttpContext.Items["forum"] as ForumBase;

            _mapper.Map(forum, forumEntity);
            await _repository.SaveAsync();
            return NoContent();
        }
        [HttpPatch("{forumId}")]
        [ServiceFilter(typeof(ValidateForumForCategoryExistsAttribute))]
        public async Task<IActionResult> PartiallyUpdateForumForCategory(int categoryId, int forumId, [FromBody] JsonPatchDocument<ForumBaseForUpdateDto> patchDoc)
        {
            if (patchDoc == null)
            {
                _logger.LogError("patchDoc object sent from client is null.");
                return BadRequest("patchDoc object is null");
            }
            var forumEntity = HttpContext.Items["forum"] as ForumBase;
            var forumToPatch = _mapper.Map<ForumBaseForUpdateDto>(forumEntity);
            patchDoc.ApplyTo(forumToPatch, ModelState);

            TryValidateModel(forumToPatch);

            if (!ModelState.IsValid)
            {
                _logger.LogError("Invalid model state for the patch document");
                return UnprocessableEntity(ModelState);
            }

            _mapper.Map(forumToPatch, forumEntity);
            await _repository.SaveAsync();
            return NoContent();
        }

    }
}

Forum/Views/Forum/ForumBase.cshtml
@using Newtonsoft.Json;
@inject UserManager<AppUser> userManager;
@model Entities.ViewModels.Forum.ForumBaseViewModel;
@{
    ViewData["Title"] = "ForumBase";
}
<script>
    function DeleteForumTopic(categoryId, forumId, topicId)
    {
        if (confirm("Вы действительно хотите удалить эту тему?")) 
        {
            if (topicId == 0) 
            {
                console.log('Тема с заданным id не найдена.');
                alert('Тема с заданным id не найдена.');
            }
            else 
            {
                $.ajax(
                    {
                        type: "POST",
                        data: { categoryId: categoryId, forumId: forumId, topicId: topicId },
                        url: "@Url.Action("DeleteTopic", "ForumHome")"
                    }).done(function (r) 
                    {
                        window.location.href = '@Url.Action("ForumTopics", "Forum")';
                    });
            }
        }
    }
</script>
<link rel="stylesheet" href="~/css/forum-style.css" />
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInRight">

                <div class="ibox-content m-b-sm border-bottom mb-4">
                    <div class="p-xs ">
                        <div class="pull-left m-r-md">
                            <i class="fa fa-globe text-navy mid-icon"></i>
                        </div>
                        <h2>@Model.ForumTitle</h2>
                    </div>
                </div>

                <div class="forum-base-create-panel btn-group-md mb-3">
                    <button type="button" class="btn btn-light" 
                    onclick="location.href='@Url.Action("ForumHome")'">Вернуться к списку форумов</button>

                    <button type="button" class="btn btn-light" 
                    onclick="location.href='@Url.RouteUrl("ForumTopicAdd",
                    new {categoryId = @Context.Request.RouteValues["categoryId"], 
                    forumId = @Context.Request.RouteValues["forumId"]})'">Создать топик</button>
                </div>

                <div class="ibox-content container">

                    @foreach (var topic in Model.Topics)
                    {
                        <div class="row ">
                            <div class="mb-3 col-lg-11">
                                <div class="row bg-light text-dark rounded">
                                    <div class="col-md-9">
                                        <div class="forum-icon">
                                            <i class="fa fa-shield"></i>
                                        </div>
                                        <a href=@Url.RouteUrl("TopicPosts",
                                       new { categoryId = @Context.Request.RouteValues["categoryId"],
                                       forumId = topic.ForumBaseId, topicId = topic.Id, pageId = 0 }) class="forum-item-title">@topic.Name</a>
                                        <div class="forum-sub-title">Автор: @topic.Author, @topic.CreatedAt</div>
                                    </div>
                                    <div class="col-md-1">
                                        <span class="font-weight-bold">
                                            @topic.TotalViews
                                        </span>
                                        <div>
                                            <small>Просмотров</small>
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <span class="font-weight-bold">
                                            @topic.TotalPosts
                                        </span>
                                        <div>
                                            <small>Ответов</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                                @if(@userManager.FindByNameAsync(@User.Identity.Name).Result.Id.Equals(topic.ForumUserId))
                                {
                                    <div class="col-1 mt-1">
                                        <button type="button" class="btn btn-light rounded"
                                                onclick="location.href='@Url.Action("DeleteTopic", "ForumHome",
                                            new { categoryId = @Context.Request.RouteValues["categoryId"],
                                            forumId = @Context.Request.RouteValues["forumId"], topicId = topic.Id})'">
                                            Удалить
                                        </button>
                                    </div>
                                } 
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Forum/Views/Forum/ForumHome.cshtml
@using Newtonsoft.Json;
@inject UserManager<AppUser> userManager;
@model Entities.ViewModels.Forum.ForumHomeViewModel;
@{
    ViewData["Title"] = "ForumHome";
}
<script>
    function msToTime(s) 
    {
        // Pad to 2 or 3 digits, default is 2
        function pad(n, z) {
            z = z || 2;
            return ('00' + n).slice(-z);
        }

        var ms = s % 1000;
        s = (s - ms) / 1000;
        var secs = s % 60;
        s = (s - secs) / 60;
        var mins = s % 60;
        var hrs = (s - mins) / 60;

        return pad(hrs) + ':' + pad(mins) + ':' + pad(secs) + '.' + pad(ms, 3);
    }
    window.addEventListener('load', (event) => 
    {
        fTime = msToTime((Date.now() - window.performance.timing.navigationStart));
        console.log('All assets are loaded')
        console.log(fTime);
        $("#lbl_loadingTime").text("Время загрузки - " + fTime);
    });
</script>
<link rel="stylesheet" href="~/css/forum-style.css" />
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInRight">

                <div class="ibox-content m-b-sm">
                    <div class="p-xs">
                        <div class="pull-left m-r-md">
                            <i class="fa fa-globe text-navy mid-icon"></i>
                        </div>
                        <h2>Добро пожаловать на форум ГУ</h2>
                    </div>
                </div>

                <div class="forum-base-create-panel btn-group-md">
                    <button type="button" class="btn btn-light" 
                    onclick="location.href='@Url.Action("RedirectToCreateCategory", "ForumCategoryCreation")'">Создать категорию</button>

                    <button type="button" class="btn btn-light" 
                    onclick="location.href='@Url.Action("RedirectToCreateForumBase", "ForumBaseCreation", 
                    new { model = JsonConvert.SerializeObject(@Model) })'">Создать форум</button>
                </div>

                <div class="ibox-content container">

                    @foreach (var cat in Model.Categories)
                    {
                        <div class="text-end">
                            <h3 class="text-success border-bottom mb-3">@cat.Name</h3>
                        </div>

                        @foreach (var forum in cat.Forums)
                        {

                            <div class="mb-4">
                                <div class="row bg-light text-dark rounded">
                                    <div class="col-8">
                                        <div class="forum-icon">
                                            <i class="fa fa-shield"></i>
                                        </div>
                                        <a href=@Url.RouteUrl("ForumTopics", 
                                        new { categoryId = forum.ForumCategoryId, forumId = forum.Id })>@forum.ForumTitle</a>
                                        <div class="forum-sub-title">forum-sub-title: @forum.ForumSubTitle</div>
                                    </div>
                                    <div class="col-sm-1">
                                        <span>
                                            @forum.TotalViews
                                        </span>
                                        <div>
                                            <small>Views</small>
                                        </div>
                                    </div>
                                    <div class="col-sm-1">
                                        <span>
                                            @forum.TopicsCount
                                        </span>
                                        <div>
                                            <small>Topics</small>
                                        </div>
                                    </div>
                                    <div class="col-sm-1">
                                        <span>
                                            @forum.TotalPosts
                                        </span>
                                        <div>
                                            <small>Posts</small>
                                        </div>
                                    </div>
                                    <div class="col-1 mt-1">
                                        @if (@userManager.FindByNameAsync(@User.Identity.Name).Result.Id.Equals(@forum.ForumUserId))
                                        {
                                            <div>
                                                <button type="button" class="btn btn-light rounded"
                                                        onclick="location.href='@Url.Action("DeleteForumBase", "ForumHome",
                                            new {categoryId = cat.Id, forumId = forum.Id})'">
                                                    Удалить
                                                </button>
                                            </div>
                                        }
                                    </div>
                                    
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>